### ISSUE TITLE
Error AddScriptToEvaluateOnNewDocumentAsync when accessing CreateDevToolsContextAsync

### ISSUE THREAD

**Issue by derodevil** [ChromiumDotNet/WebView2.DevTools.Dom#22]
OS Windows 10. Edge Version 121.0.2277.98 (Official build) (64-bit) and Visual Studio 2019. It happens a few days ago.

```
webView.CoreWebView2.DOMContentLoaded += async (e, a) =>
{
    await using var devToolsContext = await webView.CoreWebView2.CreateDevToolsContextAsync();
}
```
Here's the error message: 
`Method not found: 'System.Threading.Tasks.Task1<System.String> Microsoft.Web.WebView2.Core.DevToolsProtocolExtension.Page.AddScriptToEvaluateOnNewDocumentAsync(System.String, System.String)'.`

**Comment by derodevil** [comment]
Yes, I did. I upgraded to latest version `1.0.2271`. When I downgraded to version `1.0.824` it generated another error message `Could not load file or assembly 'Microsoft.Web.WebView2.DevToolsProtocolExtension, Version=1.0.2271.0, Culture=neutral, PublicKeyToken=2a8ab48044d2601e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

**Comment by amaitland** [comment]
Sounds like your build is in an inconsistent state from the downgrade.

**Comment by derodevil** [comment]
Well, I'll be waiting for your next release

**Comment by amaitland** [comment]
Roll back your changes then perform a clean checkout from your source control.

You should raise an issue with `Microsoft`. Upgrading to a newer patch version shouldn't include any breaking changes. This is a bug/mistake on their part.

**Comment by lucaswhob** [comment]
Hello
I Have Same problem : I Use Microsoft.Web.WebView2.DevToolsProtocolExtension Version 1.0.2271.0
and WebView2.DevTools.Dom 3.0.1.0
Exactly Same Error I Downgraded Not Work Same Error Exactly 
`Method not found: 'System.Threading.Tasks.Task1<System.String> Microsoft.Web.WebView2.Core.DevToolsProtocolExtension.Page.AddScriptToEvaluateOnNewDocumentAsync(System.String, System.String)'.`

**Comment by amaitland** [comment]
A new version has been released.

I'd still suggest that someone raise the issue with `Microsoft` so they review their process, they shouldn't be releasing breaking changes unless they release a new **major** version.
