### ISSUE TITLE
DevToolsContext does not implement System.IDisposable

### ISSUE THREAD

**Issue by pamar1908** [ChromiumDotNet/WebView2.DevTools.Dom#23]
When trying to use the extension I get an error that DevToolsContext must implement System.IDisposable:

`Using DevToolsContext = Await WebView21.CoreWebView2.CreateDevToolsContextAsync`

Also raises error for missing method:
Microsoft.Web.WebView2.Core.DevToolsProtocolExtension.Page.AddScriptToEvaluateOnNewDocumentAsync(System.String, System.String)'.'

I can see the method in code so I am not sure why this error is raised. Maybe it has something to do with how it is called.

Tested in .Net Framework 4.8

**Comment by amaitland** [comment]
> DevToolsContext does not implement System.IDisposable

That's correct. It currently only implements [IAsyncDisposable](https://learn.microsoft.com/en-us/dotnet/api/system.iasyncdisposable?view=net-8.0)

https://github.com/ChromiumDotNet/WebView2.DevTools.Dom?tab=readme-ov-file#webview2devtoolscontext
