### ISSUE TITLE
CS0576 on alias WebView2

### ISSUE THREAD

**Issue by Sandu119** [ChromiumDotNet/WebView2.DevTools.Dom#26]
### Discussed in https://github.com/ChromiumDotNet/WebView2.DevTools.Dom/discussions/25

<div type='discussions-op-text'>

<sup>Originally posted by **Sandu119** October 26, 2024</sup>
Hi,
I have a project using the WebView2 control, in which I define:
using WebView2 = Microsoft.Web.WebView2.WinForms.WebView2;  (note the alias is identical to the type name) which compiles OK
But, after adding WebView2.DevTools,DOM to the project, I get a CS0576 on that alias: Namespace '<global namespace>' contains a definition conflicting with alias 'WebView2'.
Otherwise the tool works like a charm. Thank you for the good work.
Thanks,
alex
</div>

**Comment by amaitland** [comment]
I would expect this to be a simple naming conflict, not something that can be fixed without renaming the whole library.

You've aliased `WebView2` which conflicts with `WebView2.DevTools.Dom`.

**Comment by Sandu119** [comment]
You're right, it's a simple matter of renaming the alias.
I just didn't expect the library to break my code.
